"""Turn the raw Higgsfield renders (brand/art/raw) into web assets and anchor data.

Outputs:
  client/public/dots/bodies/<shape>-<tone>.webp   (3 shapes x 8 tones, same crop per shape)
  client/public/dots/items/<category>-<name>.webp  (trimmed accessories)
  client/public/dots/manifest.json                (sizes and face anchors)
  site/dots/...                                   (copy for the landing page)
Run:  python brand/build_art.py
"""

import json
import shutil
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent
RAW = ROOT / "art" / "raw"
OUT = ROOT.parent / "client" / "public" / "dots"
SITE = ROOT.parent / "site" / "dots"
SHAPES = ["blob", "arch", "cube"]
TONES = ["pink", "orange", "yellow", "green", "teal", "blue", "violet", "slate"]
BODY_W = 480
ITEM_MAX = 420
# Items that did not look right on the bodies (floating or too big); kept in art/raw but not shipped.
EXCLUDE = {"glasses-round", "glasses-square", "glasses-monocle", "accessories-badge", "glasses-visor", "accessories-scarf", "accessories-stethoscope", "accessories-headphones", "accessories-cape"}


def strip_shadow(img):
    """Remove the soft contact shadow some renders carry below the feet."""
    a = np.array(img)
    alpha = a[:, :, 3]
    solid_rows = np.where((alpha > 215).sum(axis=1) > 3)[0]
    bottom = int(solid_rows.max())
    a[bottom + 2:, :, 3] = 0
    # clear faint, neutral shadow pixels beside the feet as well
    faint = (alpha < 150) & (np.arange(alpha.shape[0])[:, None] > bottom - 40)
    a[faint, 3] = 0
    return Image.fromarray(a)


def bbox(img, thr=24):
    alpha = np.array(img)[:, :, 3]
    ys, xs = np.where(alpha > thr)
    return xs.min(), ys.min(), xs.max() + 1, ys.max() + 1


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "bodies").mkdir(parents=True)
    (OUT / "items").mkdir(parents=True)
    manifest = {"bodies": {}, "items": {}, "tones": TONES}

    for shape in SHAPES:
        imgs = {t: strip_shadow(Image.open(RAW / "bodies" / f"{shape}-{t}.png").convert("RGBA")) for t in TONES if (RAW / "bodies" / f"{shape}-{t}.png").exists()}
        boxes = [bbox(i) for i in imgs.values()]
        x0 = min(b[0] for b in boxes); y0 = min(b[1] for b in boxes)
        x1 = max(b[2] for b in boxes); y1 = max(b[3] for b in boxes)
        w, h = x1 - x0, y1 - y0
        scale = BODY_W / w
        size = (BODY_W, round(h * scale))
        anchors = []
        for tone, img in imgs.items():
            crop = img.crop((x0, y0, x1, y1)).resize(size, Image.LANCZOS)
            crop.save(OUT / "bodies" / f"{shape}-{tone}.webp", "WEBP", quality=90, alpha_quality=100, method=6)
            arr = np.array(crop).astype(float)
            luma = arr[:, :, :3].mean(axis=2)
            dark = (luma < 60) & (arr[:, :, 3] > 200)
            H, W = dark.shape
            dark[int(H * 0.62):, :] = False
            dark[:int(H * 0.10), :] = False
            ys, xs = np.where(dark)
            if len(xs) < 20:
                continue
            mid = W / 2
            left = xs < mid
            if left.sum() < 5 or (~left).sum() < 5:
                continue
            anchors.append([xs[left].mean() / W, xs[~left].mean() / W, ys.mean() / H])
        ax = np.mean(anchors, axis=0)
        # width of the body at eye level (torso without arms)
        alpha = np.array(Image.open(OUT / "bodies" / f"{shape}-{TONES[5]}.webp"))[:, :, 3]
        row = alpha[int(ax[2] * alpha.shape[0])] > 128
        cols = np.where(row)[0]
        manifest["bodies"][shape] = {
            "w": size[0], "h": size[1], "eyeL": round(float(ax[0]), 4), "eyeR": round(float(ax[1]), 4),
            "eyeY": round(float(ax[2]), 4), "headW": round(float((cols.max() - cols.min()) / size[0]), 4),
            "headL": round(float(cols.min() / size[0]), 4),
        }
        print(shape, manifest["bodies"][shape])

    for cat in ("hats", "glasses", "accessories"):
        for f in sorted((RAW / cat).glob("*.png")):
            if f"{cat}-{f.stem}" in EXCLUDE:
                continue
            img = Image.open(f).convert("RGBA")
            img = img.crop(bbox(img, 12))
            k = ITEM_MAX / max(img.size)
            img = img.resize((round(img.width * k), round(img.height * k)), Image.LANCZOS)
            name = f"{cat}-{f.stem}"
            if name in EXCLUDE:
                continue
            img.save(OUT / "items" / f"{name}.webp", "WEBP", quality=90, alpha_quality=100, method=6)
            manifest["items"][name] = {"w": img.width, "h": img.height}

    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    data_js = ROOT.parent / "client" / "lib" / "dotSpriteData.js"
    data_js.write_text("/* Generated by brand/build_art.py: sizes and face anchors of the plush Dot art. */\nexport const MANIFEST = " + json.dumps(manifest, separators=(",", ":")) + ";\n", encoding="utf-8")
    if SITE.exists():
        shutil.rmtree(SITE)
    shutil.copytree(OUT, SITE)
    total = sum(p.stat().st_size for p in OUT.rglob("*.webp")) / 1e6
    print(f"{len(list(OUT.rglob('*.webp')))} files, {total:.1f} MB")


if __name__ == "__main__":
    main()
