/* Plush-style Dots built from layered images (bodies, hats, glasses, accessories).
   Returns an HTML string so React and the landing page share the same renderer.
   Body anchors come from public/dots/manifest.json (see dotSpriteData.js, generated by brand/build_art.py). */

import { MANIFEST } from './dotSpriteData';

export const BODIES = ['blob', 'arch', 'cube'];
export const TONES = ['pink', 'orange', 'yellow', 'green', 'teal', 'blue', 'violet', 'slate'];
export const TONE_COLORS = { pink: '#ff4d7d', orange: '#ff8a3d', yellow: '#ffc21a', green: '#7cd13b', teal: '#19c3a6', blue: '#2f7bff', violet: '#7a4cf0', slate: '#52657a' };
export const SPRITE_ITEMS = {
  hat: ['none', 'cap', 'beanie', 'tophat', 'crown', 'party', 'cowboy', 'wizard', 'chef', 'graduation', 'hardhat', 'antenna', 'flower'],
  glasses: ['none', 'round', 'square', 'shades', 'monocle', 'visor'],
  accessory: ['none', 'bowtie', 'tie', 'scarf', 'stethoscope', 'headphones', 'mustache', 'badge', 'cape'],
};
export const DEFAULT_SPRITE_LOOK = { body: 'blob', tone: 'violet', hat: 'none', glasses: 'none', accessory: 'none' };
const FOLDER = { hat: 'hats', glasses: 'glasses', accessory: 'accessories' };

// [width as a share of the head width, how far the hat sinks into the head as a share of body height]
const HAT = {
  cap: [1.0, 0.1], beanie: [1.02, 0.09], tophat: [0.82, 0.1], crown: [0.74, 0.07], party: [0.58, 0.06], cowboy: [1.32, 0.16],
  wizard: [1.0, 0.09], chef: [0.94, 0.1], graduation: [1.08, 0.13], hardhat: [1.0, 0.09], antenna: [0.3, 0.05], flower: [0.4, -0.02],
};

export function normalizeSpriteLook(look) {
  const l = look || {};
  const pick = (v, list, d) => (list.includes(v) ? v : d);
  return {
    body: pick(l.body, BODIES, DEFAULT_SPRITE_LOOK.body),
    tone: pick(l.tone, TONES, DEFAULT_SPRITE_LOOK.tone),
    hat: pick(l.hat, SPRITE_ITEMS.hat, 'none'),
    glasses: pick(l.glasses, SPRITE_ITEMS.glasses, 'none'),
    accessory: pick(l.accessory, SPRITE_ITEMS.accessory, 'none'),
  };
}

export function isSpriteLook(look) {
  return !!look && BODIES.includes(look.body);
}

const pct = (v) => `${(v * 100).toFixed(2)}%`;

/** Layout of a Dot inside a square frame (all numbers are shares of the frame). */
export function spriteLayout(look) {
  const l = normalizeSpriteLook(look);
  const B = MANIFEST.bodies[l.body];
  let bh = 0.58;
  let bw = (bh * B.w) / B.h;
  if (bw > 0.84) { bw = 0.84; bh = (bw * B.h) / B.w; }
  const left = (1 - bw) / 2;
  const top = 1 - 0.05 - bh;
  const fx = (f) => left + f * bw;
  const fy = (f) => top + f * bh;
  return { l, B, bw, bh, left, top, fx, fy, eyeCx: fx((B.eyeL + B.eyeR) / 2), eyeY: fy(B.eyeY), eyeGap: (B.eyeR - B.eyeL) * bw, headW: B.headW * bw };
}

function item(cat, name, x, y, w, extra = '') {
  const meta = MANIFEST.items[`${FOLDER[cat]}-${name}`];
  if (!meta) return '';
  const h = (w * meta.h) / meta.w;
  return { w, h, x, y, meta, extra };
}

function img(base, cat, name, box, z, cls) {
  if (!box) return '';
  return `<img class="dsp-${cls}" src="${base}items/${FOLDER[cat]}-${name}.webp" alt="" draggable="false" style="left:${pct(box.x)};top:${pct(box.y)};width:${pct(box.w)};height:${pct(box.h)};z-index:${z}">`;
}

/** HTML for a plush Dot. `size` is the frame size in px; `base` is where /dots/ is served. */
export function dotSprite(look, size = 96, label = 'Dot', base = '/dots/') {
  const g = spriteLayout(look);
  const { l } = g;
  const parts = [];
  // cape sits behind the body
  if (l.accessory === 'cape') {
    const w = g.headW * 1.5;
    const box = item('accessory', 'cape', g.eyeCx - w / 2, g.eyeY - 0.03, w);
    parts.push(img(base, 'accessory', 'cape', box, 1, 'cape'));
  }
  parts.push(`<img class="dsp-body" src="${base}bodies/${l.body}-${l.tone}.webp" alt="" draggable="false" style="left:${pct(g.left)};top:${pct(g.top)};width:${pct(g.bw)};height:${pct(g.bh)};z-index:2">`);
  if (l.accessory !== 'none' && l.accessory !== 'cape') {
    let box;
    const cx = g.eyeCx;
    const ey = g.eyeY;
    const hw = g.headW;
    const it = (name, w, anchorY = 0.5, dy = 0, dx = 0) => {
      const b = item('accessory', name, 0, 0, w);
      if (!b) return null;
      b.x = cx + dx - w / 2;
      b.y = ey + dy - b.h * anchorY;
      return b;
    };
    if (l.accessory === 'bowtie') box = it('bowtie', hw * 0.44, 0.5, g.bh * 0.3);
    else if (l.accessory === 'tie') box = it('tie', hw * 0.22, 0, g.bh * 0.22);
    else if (l.accessory === 'scarf') box = it('scarf', hw * 0.8, 0.28, g.bh * 0.36);
    else if (l.accessory === 'stethoscope') box = it('stethoscope', hw * 0.4, 0, g.bh * 0.12);
    else if (l.accessory === 'headphones') box = it('headphones', hw * 1.2, 0.66, 0);
    else if (l.accessory === 'mustache') box = it('mustache', hw * 0.36, 0.5, g.bh * 0.13);
    else if (l.accessory === 'badge') box = it('badge', hw * 0.21, 0.5, g.bh * 0.32, hw * 0.28);
    parts.push(img(base, 'accessory', l.accessory, box, l.accessory === 'headphones' ? 3 : 4, 'acc'));
  }
  if (l.glasses !== 'none') {
    const gap = g.eyeGap;
    let box;
    const mk = (w, anchorY, dy, dx) => {
      const b = item('glasses', l.glasses, 0, 0, w);
      if (!b) return null;
      b.x = g.eyeCx + dx - w / 2;
      b.y = g.eyeY + dy - b.h * anchorY;
      return b;
    };
    if (l.glasses === 'monocle') box = mk(gap * 0.92, 0.28, 0, gap / 2);
    else if (l.glasses === 'visor') box = mk(g.headW * 0.96, 0.5, 0, 0);
    else box = mk(gap * 2.15, 0.5, 0, 0);
    parts.push(img(base, 'glasses', l.glasses, box, 5, 'gl'));
  }
  if (l.hat !== 'none') {
    const [wf, sink] = HAT[l.hat];
    const w = g.headW * wf;
    const meta = MANIFEST.items[`hats-${l.hat}`];
    if (meta) {
      const h = (w * meta.h) / meta.w;
      const cx = g.eyeCx + (l.hat === 'flower' ? g.headW * 0.3 : 0);
      const bottom = g.top + sink * g.bh + (l.hat === 'flower' ? g.bh * 0.1 : 0);
      parts.push(img(base, 'hat', l.hat, { x: cx - w / 2, y: bottom - h, w, h }, 6, 'hat'));
    }
  }
  const safe = String(label).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  return `<span class="dsp" role="img" aria-label="${safe}" style="--s:${size}px"><span class="dsp-all">${parts.join('')}</span><span class="dsp-shadow" style="left:${pct(g.left + g.bw * 0.1)};width:${pct(g.bw * 0.8)};top:${pct(g.top + g.bh - 0.012)}"></span></span>`;
}

export const SPRITE_CSS = `
.dsp{position:relative;display:inline-block;width:var(--s,96px);height:var(--s,96px);flex:none;line-height:0}
.dsp-all{position:absolute;inset:0;display:block;transform-origin:50% 95%}
.dsp img{position:absolute;pointer-events:none;user-select:none;-webkit-user-drag:none;max-width:none}
.dsp-shadow{position:absolute;height:5%;border-radius:50%;background:radial-gradient(closest-side,rgba(0,0,0,.28),rgba(0,0,0,0));z-index:0}
.dl .dsp-all{animation:dl-breathe var(--dl-speed,3.6s) ease-in-out var(--dl-delay,0s) infinite}
.dl[data-state=happy] .dsp-all{animation:dl-hop .55s cubic-bezier(.2,.8,.3,1)}
.dl[data-state=sleepy] .dsp-all{animation:dl-breathe 6s ease-in-out infinite}
.dl[data-state=talking] .dsp-all{animation:dl-talk-body .32s ease-in-out infinite}
.dl[data-state=thinking] .dsp-all{animation:dl-think 2.4s ease-in-out infinite}
@keyframes dl-talk-body{0%,100%{transform:scale(1,1)}50%{transform:scale(1.03,.97)}}
@keyframes dl-think{0%,100%{transform:rotate(-3deg)}50%{transform:rotate(3deg)}}
`;

export function ensureSpriteStyles() {
  if (typeof document === 'undefined' || document.getElementById('dot-sprite-css')) return;
  const style = document.createElement('style');
  style.id = 'dot-sprite-css';
  style.textContent = SPRITE_CSS;
  document.head.appendChild(style);
}

export function randomSpriteLook() {
  const pick = (a) => a[Math.floor(Math.random() * a.length)];
  return {
    body: pick(BODIES), tone: pick(TONES),
    hat: Math.random() < 0.85 ? pick(SPRITE_ITEMS.hat.slice(1)) : 'none',
    glasses: Math.random() < 0.5 ? pick(SPRITE_ITEMS.glasses.slice(1)) : 'none',
    accessory: Math.random() < 0.6 ? pick(SPRITE_ITEMS.accessory.slice(1)) : 'none',
  };
}
